/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";
import { GizmoError } from "./gizmoerror.js";

/**
 * Rate limit exceeded
 */
export type CreateApplicationRateLimitedErrorData = {
  kind: "RateLimited";
  name: string;
  retryAfter: number;
};

/**
 * Rate limit exceeded
 */
export class CreateApplicationRateLimitedError extends GizmoError {
  kind: "RateLimited";
  retryAfter: number;

  /** The original data that was passed to this error instance. */
  data$: CreateApplicationRateLimitedErrorData;

  constructor(
    err: CreateApplicationRateLimitedErrorData,
    httpMeta: { response: Response; request: Request; body: string },
  ) {
    const message = "message" in err && typeof err.message === "string"
      ? err.message
      : `API error occurred: ${JSON.stringify(err)}`;
    super(message, httpMeta);
    this.data$ = err;
    this.kind = err.kind;
    this.retryAfter = err.retryAfter;

    this.name = "CreateApplicationRateLimitedError";
  }
}

/** @internal */
export const CreateApplicationRateLimitedError$inboundSchema: z.ZodType<
  CreateApplicationRateLimitedError,
  z.ZodTypeDef,
  unknown
> = z.object({
  kind: z.literal("RateLimited"),
  name: z.string(),
  retryAfter: z.number(),
  request$: z.instanceof(Request),
  response$: z.instanceof(Response),
  body$: z.string(),
})
  .transform((v) => {
    return new CreateApplicationRateLimitedError(v, {
      request: v.request$,
      response: v.response$,
      body: v.body$,
    });
  });
