/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";
import { GizmoError } from "./gizmoerror.js";

/**
 * Rate limit exceeded
 */
export type UpdateApplicationRateLimitedErrorData = {
  kind: "RateLimited";
  name: string;
  retryAfter: number;
};

/**
 * Rate limit exceeded
 */
export class UpdateApplicationRateLimitedError extends GizmoError {
  kind: "RateLimited";
  retryAfter: number;

  /** The original data that was passed to this error instance. */
  data$: UpdateApplicationRateLimitedErrorData;

  constructor(
    err: UpdateApplicationRateLimitedErrorData,
    httpMeta: { response: Response; request: Request; body: string },
  ) {
    const message = "message" in err && typeof err.message === "string"
      ? err.message
      : `API error occurred: ${JSON.stringify(err)}`;
    super(message, httpMeta);
    this.data$ = err;
    this.kind = err.kind;
    this.retryAfter = err.retryAfter;

    this.name = "UpdateApplicationRateLimitedError";
  }
}

/** @internal */
export const UpdateApplicationRateLimitedError$inboundSchema: z.ZodType<
  UpdateApplicationRateLimitedError,
  z.ZodTypeDef,
  unknown
> = z.object({
  kind: z.literal("RateLimited"),
  name: z.string(),
  retryAfter: z.number(),
  request$: z.instanceof(Request),
  response$: z.instanceof(Response),
  body$: z.string(),
})
  .transform((v) => {
    return new UpdateApplicationRateLimitedError(v, {
      request: v.request$,
      response: v.response$,
      body: v.body$,
    });
  });

/** @internal */
export type UpdateApplicationRateLimitedError$Outbound = {
  kind: "RateLimited";
  name: string;
  retryAfter: number;
};

/** @internal */
export const UpdateApplicationRateLimitedError$outboundSchema: z.ZodType<
  UpdateApplicationRateLimitedError$Outbound,
  z.ZodTypeDef,
  UpdateApplicationRateLimitedError
> = z.instanceof(UpdateApplicationRateLimitedError)
  .transform(v => v.data$)
  .pipe(z.object({
    kind: z.literal("RateLimited"),
    name: z.string(),
    retryAfter: z.number(),
  }));

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace UpdateApplicationRateLimitedError$ {
  /** @deprecated use `UpdateApplicationRateLimitedError$inboundSchema` instead. */
  export const inboundSchema = UpdateApplicationRateLimitedError$inboundSchema;
  /** @deprecated use `UpdateApplicationRateLimitedError$outboundSchema` instead. */
  export const outboundSchema =
    UpdateApplicationRateLimitedError$outboundSchema;
  /** @deprecated use `UpdateApplicationRateLimitedError$Outbound` instead. */
  export type Outbound = UpdateApplicationRateLimitedError$Outbound;
}
