/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { applicationsCreate } from "../funcs/applicationsCreate.js";
import { applicationsGet } from "../funcs/applicationsGet.js";
import { applicationsUpdate } from "../funcs/applicationsUpdate.js";
import { ClientSDK, RequestOptions } from "../lib/sdks.js";
import * as models from "../models/index.js";
import * as operations from "../models/operations/index.js";
import { unwrapAsync } from "../types/fp.js";

export class Applications extends ClientSDK {
  /**
   * Get Application
   */
  async get(
    id: string,
    options?: RequestOptions,
  ): Promise<models.Application> {
    return unwrapAsync(applicationsGet(
      this,
      id,
      options,
    ));
  }

  /**
   * Update Application
   */
  async update(
    id: string,
    requestBody: operations.UpdateApplicationRequestBody,
    options?: RequestOptions,
  ): Promise<any> {
    return unwrapAsync(applicationsUpdate(
      this,
      id,
      requestBody,
      options,
    ));
  }

  /**
   * Create Application
   */
  async create(
    request?: operations.CreateApplicationRequest | undefined,
    options?: RequestOptions,
  ): Promise<operations.CreateApplicationResponse> {
    return unwrapAsync(applicationsCreate(
      this,
      request,
      options,
    ));
  }
}
