/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { ClientSDK } from "../lib/sdks.js";
import { Applications } from "./applications.js";

export class Gizmo extends ClientSDK {
  private _applications?: Applications;
  get applications(): Applications {
    return (this._applications ??= new Applications(this._options));
  }
}
