/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { ClientSDK } from "../lib/sdks.js";
import { Application } from "./application.js";

export class Gizmo extends ClientSDK {
  private _application?: Application;
  get application(): Application {
    return (this._application ??= new Application(this._options));
  }
}
