/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import dotenv from "dotenv";
dotenv.config();
/**
 * Example usage of the @gizmo-os/sdk SDK
 *
 * To run this example from the examples directory:
 * npm run build && npx tsx applicationGetApplication.example.ts
 */

import { Gizmo } from "@gizmo-os/sdk";

const gizmo = new Gizmo({
  bearerAuth: process.env["GIZMO_BEARER_AUTH"] ?? "",
});

async function main() {
  const result = await gizmo.application.getApplication("423");

  console.log(result);
}

main().catch(console.error);
