workflowVersion: 1.0.0
speakeasyVersion: latest
sources:
    Gizmo REST API:
        inputs:
            - location: openapi.yaml
        overlays:
            - location: .speakeasy/speakeasy-modifications-overlay.yaml
        output: .speakeasy/out.openapi.yaml
        registry:
            location: registry.speakeasyapi.dev/gizmo-2xw/prod/gizmo-rest-api
    mintlify:
        inputs:
            - location: openapi.yaml
        overlays:
            - location: code-samples-overlay.yaml
targets:
    gizmo:
        target: typescript
        source: Gizmo REST API
        publish:
            npm:
                token: $npm_token
        codeSamples:
            registry:
                location: registry.speakeasyapi.dev/gizmo-2xw/prod/gizmo-rest-api-typescript-code-samples
            labelOverride:
                fixedValue: Typescript (SDK)
            blocking: false
