workflowVersion: 1.0.0
speakeasyVersion: latest
sources:
    main:
        inputs:
            - location: https://polished-gerbil-615.convex.site/doc
        registry:
            location: registry.speakeasyapi.dev/gizmo-2xw/prod/main
targets:
    gizmo:
        target: typescript
        source: main
        codeSamples:
            registry:
                location: registry.speakeasyapi.dev/gizmo-2xw/prod/main
