workflowVersion: 1.0.0
speakeasyVersion: latest
sources:
    main:
        inputs:
            - location: https://core.usegizmo.com/doc
        overlays:
            - location: .speakeasy/speakeasy-modifications-overlay-1.yaml
        output: ./openapi.yaml
        registry:
            location: registry.speakeasyapi.dev/gizmo-2xw/prod/main
targets:
    gizmo:
        target: typescript
        source: main
        publish:
            npm:
                token: $npm_token
        codeSamples:
            registry:
                location: registry.speakeasyapi.dev/gizmo-2xw/prod/main-typescript-code-samples
            labelOverride:
                fixedValue: Typescript (SDK)
            blocking: false
