/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";
import * as models from "../index.js";

export type CreateApplicationRequest = {
  primaryBorrowerFirstName: string;
  primaryBorrowerLastName: string;
  primaryBorrowerEmail: string;
  primaryBorrowerPhone: string;
  primaryBorrowerDateOfBirth?: string | undefined;
  primaryBorrowerSsn?: string | undefined;
  /**
   * The two-letter state abbreviation in lowercase
   */
  subjectPropertyState: models.State;
  subjectPropertyStreetAddress?: string | undefined;
  subjectPropertyCity?: string | undefined;
  subjectPropertyZip?: string | undefined;
  loanPurpose?: models.LoanPurpose | undefined;
  losId?: string | undefined;
  crmId?: string | undefined;
  leadProviderSlug: string;
  teamId?: string | undefined;
};

/**
 * The created Application ID
 */
export type CreateApplicationResponse = {
  id: string;
};

/** @internal */
export type CreateApplicationRequest$Outbound = {
  primaryBorrowerFirstName: string;
  primaryBorrowerLastName: string;
  primaryBorrowerEmail: string;
  primaryBorrowerPhone: string;
  primaryBorrowerDateOfBirth?: string | undefined;
  primaryBorrowerSsn?: string | undefined;
  subjectPropertyState: string;
  subjectPropertyStreetAddress?: string | undefined;
  subjectPropertyCity?: string | undefined;
  subjectPropertyZip?: string | undefined;
  loanPurpose?: string | undefined;
  losId?: string | undefined;
  crmId?: string | undefined;
  leadProviderSlug: string;
  teamId?: string | undefined;
};

/** @internal */
export const CreateApplicationRequest$outboundSchema: z.ZodType<
  CreateApplicationRequest$Outbound,
  z.ZodTypeDef,
  CreateApplicationRequest
> = z.object({
  primaryBorrowerFirstName: z.string(),
  primaryBorrowerLastName: z.string(),
  primaryBorrowerEmail: z.string(),
  primaryBorrowerPhone: z.string(),
  primaryBorrowerDateOfBirth: z.string().optional(),
  primaryBorrowerSsn: z.string().optional(),
  subjectPropertyState: models.State$outboundSchema,
  subjectPropertyStreetAddress: z.string().optional(),
  subjectPropertyCity: z.string().optional(),
  subjectPropertyZip: z.string().optional(),
  loanPurpose: models.LoanPurpose$outboundSchema.optional(),
  losId: z.string().optional(),
  crmId: z.string().optional(),
  leadProviderSlug: z.string(),
  teamId: z.string().optional(),
});

export function createApplicationRequestToJSON(
  createApplicationRequest: CreateApplicationRequest,
): string {
  return JSON.stringify(
    CreateApplicationRequest$outboundSchema.parse(createApplicationRequest),
  );
}

/** @internal */
export const CreateApplicationResponse$inboundSchema: z.ZodType<
  CreateApplicationResponse,
  z.ZodTypeDef,
  unknown
> = z.object({
  id: z.string(),
});

export function createApplicationResponseFromJSON(
  jsonString: string,
): SafeParseResult<CreateApplicationResponse, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => CreateApplicationResponse$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'CreateApplicationResponse' from JSON`,
  );
}
