/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";

export type GetApplicationRequest = {
  id: string;
};

/** @internal */
export type GetApplicationRequest$Outbound = {
  id: string;
};

/** @internal */
export const GetApplicationRequest$outboundSchema: z.ZodType<
  GetApplicationRequest$Outbound,
  z.ZodTypeDef,
  GetApplicationRequest
> = z.object({
  id: z.string(),
});

export function getApplicationRequestToJSON(
  getApplicationRequest: GetApplicationRequest,
): string {
  return JSON.stringify(
    GetApplicationRequest$outboundSchema.parse(getApplicationRequest),
  );
}
