/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { remap as remap$ } from "../../lib/primitives.js";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";
import * as models from "../index.js";

export type UpdateApplicationRequest = {
  id: string;
  applicationPatch: models.ApplicationPatch;
};

/** @internal */
export const UpdateApplicationRequest$inboundSchema: z.ZodType<
  UpdateApplicationRequest,
  z.ZodTypeDef,
  unknown
> = z.object({
  id: z.string(),
  ApplicationPatch: models.ApplicationPatch$inboundSchema,
}).transform((v) => {
  return remap$(v, {
    "ApplicationPatch": "applicationPatch",
  });
});

/** @internal */
export type UpdateApplicationRequest$Outbound = {
  id: string;
  ApplicationPatch: models.ApplicationPatch$Outbound;
};

/** @internal */
export const UpdateApplicationRequest$outboundSchema: z.ZodType<
  UpdateApplicationRequest$Outbound,
  z.ZodTypeDef,
  UpdateApplicationRequest
> = z.object({
  id: z.string(),
  applicationPatch: models.ApplicationPatch$outboundSchema,
}).transform((v) => {
  return remap$(v, {
    applicationPatch: "ApplicationPatch",
  });
});

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace UpdateApplicationRequest$ {
  /** @deprecated use `UpdateApplicationRequest$inboundSchema` instead. */
  export const inboundSchema = UpdateApplicationRequest$inboundSchema;
  /** @deprecated use `UpdateApplicationRequest$outboundSchema` instead. */
  export const outboundSchema = UpdateApplicationRequest$outboundSchema;
  /** @deprecated use `UpdateApplicationRequest$Outbound` instead. */
  export type Outbound = UpdateApplicationRequest$Outbound;
}

export function updateApplicationRequestToJSON(
  updateApplicationRequest: UpdateApplicationRequest,
): string {
  return JSON.stringify(
    UpdateApplicationRequest$outboundSchema.parse(updateApplicationRequest),
  );
}

export function updateApplicationRequestFromJSON(
  jsonString: string,
): SafeParseResult<UpdateApplicationRequest, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => UpdateApplicationRequest$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'UpdateApplicationRequest' from JSON`,
  );
}
