/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";
import { remap as remap$ } from "../../lib/primitives.js";
import * as models from "../index.js";

export type UpdateApplicationRequestBody = {
  loanPurpose?: models.LoanPurpose | undefined;
  crmId?: string | undefined;
  losId?: string | undefined;
  primaryBorrowerDateOfBirth?: string | undefined;
  primaryBorrowerSsn?: string | undefined;
  primaryBorrowerEmail?: string | undefined;
  primaryBorrowerFirstName?: string | undefined;
  primaryBorrowerLastName?: string | undefined;
  primaryBorrowerPhone?: string | undefined;
  status?: models.Milestone | undefined;
  subjectPropertyCity?: string | undefined;
  /**
   * The two-letter state abbreviation in lowercase
   */
  subjectPropertyState?: models.State | undefined;
  subjectPropertyStreetAddress?: string | undefined;
  subjectPropertyZip?: string | undefined;
  teamId?: string | undefined;
};

export type UpdateApplicationRequest = {
  id: string;
  requestBody: UpdateApplicationRequestBody;
};

/** @internal */
export type UpdateApplicationRequestBody$Outbound = {
  loanPurpose?: string | undefined;
  crmId?: string | undefined;
  losId?: string | undefined;
  primaryBorrowerDateOfBirth?: string | undefined;
  primaryBorrowerSsn?: string | undefined;
  primaryBorrowerEmail?: string | undefined;
  primaryBorrowerFirstName?: string | undefined;
  primaryBorrowerLastName?: string | undefined;
  primaryBorrowerPhone?: string | undefined;
  status?: string | undefined;
  subjectPropertyCity?: string | undefined;
  subjectPropertyState?: string | undefined;
  subjectPropertyStreetAddress?: string | undefined;
  subjectPropertyZip?: string | undefined;
  teamId?: string | undefined;
};

/** @internal */
export const UpdateApplicationRequestBody$outboundSchema: z.ZodType<
  UpdateApplicationRequestBody$Outbound,
  z.ZodTypeDef,
  UpdateApplicationRequestBody
> = z.object({
  loanPurpose: models.LoanPurpose$outboundSchema.optional(),
  crmId: z.string().optional(),
  losId: z.string().optional(),
  primaryBorrowerDateOfBirth: z.string().optional(),
  primaryBorrowerSsn: z.string().optional(),
  primaryBorrowerEmail: z.string().optional(),
  primaryBorrowerFirstName: z.string().optional(),
  primaryBorrowerLastName: z.string().optional(),
  primaryBorrowerPhone: z.string().optional(),
  status: models.Milestone$outboundSchema.optional(),
  subjectPropertyCity: z.string().optional(),
  subjectPropertyState: models.State$outboundSchema.optional(),
  subjectPropertyStreetAddress: z.string().optional(),
  subjectPropertyZip: z.string().optional(),
  teamId: z.string().optional(),
});

export function updateApplicationRequestBodyToJSON(
  updateApplicationRequestBody: UpdateApplicationRequestBody,
): string {
  return JSON.stringify(
    UpdateApplicationRequestBody$outboundSchema.parse(
      updateApplicationRequestBody,
    ),
  );
}

/** @internal */
export type UpdateApplicationRequest$Outbound = {
  id: string;
  RequestBody: UpdateApplicationRequestBody$Outbound;
};

/** @internal */
export const UpdateApplicationRequest$outboundSchema: z.ZodType<
  UpdateApplicationRequest$Outbound,
  z.ZodTypeDef,
  UpdateApplicationRequest
> = z.object({
  id: z.string(),
  requestBody: z.lazy(() => UpdateApplicationRequestBody$outboundSchema),
}).transform((v) => {
  return remap$(v, {
    requestBody: "RequestBody",
  });
});

export function updateApplicationRequestToJSON(
  updateApplicationRequest: UpdateApplicationRequest,
): string {
  return JSON.stringify(
    UpdateApplicationRequest$outboundSchema.parse(updateApplicationRequest),
  );
}
