/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";
import { safeParse } from "../lib/schemas.js";
import { Result as SafeParseResult } from "../types/fp.js";
import { SDKValidationError } from "./errors/sdkvalidationerror.js";
import { LoanPurpose, LoanPurpose$inboundSchema } from "./loanpurpose.js";
import { Milestone, Milestone$inboundSchema } from "./milestone.js";
import { State, State$inboundSchema } from "./state.js";

/**
 * The Application object
 */
export type Application = {
  id: string;
  orgId: string;
  createdAt: number;
  updatedAt?: number | undefined;
  status: Milestone;
  primaryBorrowerFirstName: string;
  primaryBorrowerLastName: string;
  primaryBorrowerEmail: string;
  primaryBorrowerPhone: string;
  primaryBorrowerDateOfBirth?: string | undefined;
  primaryBorrowerSsn?: string | undefined;
  /**
   * The two-letter state abbreviation in lowercase
   */
  subjectPropertyState: State;
  subjectPropertyStreetAddress?: string | undefined;
  subjectPropertyCity?: string | undefined;
  subjectPropertyZip?: string | undefined;
  loanPurpose?: LoanPurpose | undefined;
  losId?: string | undefined;
  crmId?: string | undefined;
  leadProviderSlug: string;
  teamId?: string | undefined;
};

/** @internal */
export const Application$inboundSchema: z.ZodType<
  Application,
  z.ZodTypeDef,
  unknown
> = z.object({
  id: z.string(),
  orgId: z.string(),
  createdAt: z.number(),
  updatedAt: z.number().optional(),
  status: Milestone$inboundSchema,
  primaryBorrowerFirstName: z.string(),
  primaryBorrowerLastName: z.string(),
  primaryBorrowerEmail: z.string(),
  primaryBorrowerPhone: z.string(),
  primaryBorrowerDateOfBirth: z.string().optional(),
  primaryBorrowerSsn: z.string().optional(),
  subjectPropertyState: State$inboundSchema,
  subjectPropertyStreetAddress: z.string().optional(),
  subjectPropertyCity: z.string().optional(),
  subjectPropertyZip: z.string().optional(),
  loanPurpose: LoanPurpose$inboundSchema.optional(),
  losId: z.string().optional(),
  crmId: z.string().optional(),
  leadProviderSlug: z.string(),
  teamId: z.string().optional(),
});

export function applicationFromJSON(
  jsonString: string,
): SafeParseResult<Application, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => Application$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'Application' from JSON`,
  );
}
