/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";
import { ClosedEnum } from "../types/enums.js";

export const LoanPurpose = {
  Purchase: "purchase",
  Refi: "refi",
  RefiCashOut: "refiCashOut",
} as const;
export type LoanPurpose = ClosedEnum<typeof LoanPurpose>;

/** @internal */
export const LoanPurpose$inboundSchema: z.ZodNativeEnum<typeof LoanPurpose> = z
  .nativeEnum(LoanPurpose);
/** @internal */
export const LoanPurpose$outboundSchema: z.ZodNativeEnum<typeof LoanPurpose> =
  LoanPurpose$inboundSchema;
