/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { ClosedEnum } from "../types/enums.js";

export const LoanPurpose = {
  Purchase: "purchase",
  Refi: "refi",
  RefiCashOut: "refiCashOut",
} as const;
export type LoanPurpose = ClosedEnum<typeof LoanPurpose>;

/** @internal */
export const LoanPurpose$inboundSchema: z.ZodNativeEnum<typeof LoanPurpose> = z
  .nativeEnum(LoanPurpose);

/** @internal */
export const LoanPurpose$outboundSchema: z.ZodNativeEnum<typeof LoanPurpose> =
  LoanPurpose$inboundSchema;

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace LoanPurpose$ {
  /** @deprecated use `LoanPurpose$inboundSchema` instead. */
  export const inboundSchema = LoanPurpose$inboundSchema;
  /** @deprecated use `LoanPurpose$outboundSchema` instead. */
  export const outboundSchema = LoanPurpose$outboundSchema;
}
