/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";
import { ClosedEnum } from "../types/enums.js";

export const Milestone = {
  New: "NEW",
  Attempted: "ATTEMPTED",
  Contacted: "CONTACTED",
  CreditPulled: "CREDIT_PULLED",
  PreApproved: "PRE_APPROVED",
  Application: "APPLICATION",
  Processing: "PROCESSING",
  Submittal: "SUBMITTAL",
  Resubmittal: "RESUBMITTAL",
  ConditionallyApproved: "CONDITIONALLY_APPROVED",
  FinalApproved: "FINAL_APPROVED",
  DocsOut: "DOCS_OUT",
  Funded: "FUNDED",
  Purchased: "PURCHASED",
  Completed: "COMPLETED",
  Withdrawn: "WITHDRAWN",
  Denied: "DENIED",
} as const;
export type Milestone = ClosedEnum<typeof Milestone>;

/** @internal */
export const Milestone$inboundSchema: z.ZodNativeEnum<typeof Milestone> = z
  .nativeEnum(Milestone);
/** @internal */
export const Milestone$outboundSchema: z.ZodNativeEnum<typeof Milestone> =
  Milestone$inboundSchema;
